# Generated by Django 2.2.3 on 2020-04-02 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', django_google_maps.fields.AddressField(max_length=200)),
                ('geolocation', django_google_maps.fields.GeoLocationField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(blank=True, default=3)),
                ('email', models.EmailField(default='veganation@gmail.com', max_length=254)),
                ('veganSince', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to='profile_images')),
                ('quote', models.TextField(blank=True, max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=40)),
                ('firstName', models.CharField(blank=True, max_length=30)),
                ('lastName', models.CharField(blank=True, max_length=40)),
                ('age', models.IntegerField(default=20)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myaccount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=128)),
                ('hug_rate', models.IntegerField(blank=True, null=True)),
                ('seren_rate', models.IntegerField(blank=True, null=True)),
                ('the78_rate', models.IntegerField(blank=True, null=True)),
                ('glasvegan_rate', models.IntegerField(blank=True, null=True)),
                ('puti_rate', models.IntegerField(blank=True, null=True)),
                ('mono_rate', models.IntegerField(blank=True, null=True)),
                ('picnic_rate', models.IntegerField(blank=True, null=True)),
                ('vandv_rate', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField(default=django.utils.timezone.now)),
                ('rest', models.IntegerField(default=2)),
                ('age', models.IntegerField(default=5)),
                ('gender', models.IntegerField(default=2)),
                ('myage', models.IntegerField(default=5)),
                ('mygender', models.IntegerField(default=2)),
                ('userBuddy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
