# Generated by Django 3.0.3 on 2020-03-17 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0002_auto_20200317_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='veganSince',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
