# Generated by Django 2.2.1 on 2020-03-20 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0005_rental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lastName',
        ),
    ]
