# Generated by Django 2.2.1 on 2020-03-20 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0006_auto_20200320_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profilePic',
            new_name='picture',
        ),
    ]
