# Generated by Django 2.2.3 on 2020-03-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0009_auto_20200320_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='picture',
            new_name='image',
        ),
    ]
