# Generated by Django 2.2.3 on 2020-03-28 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0010_auto_20200328_1544'),
        ('veganation', '0010_auto_20200328_1446'),
    ]

    operations = [
    ]
