# Generated by Django 2.2.3 on 2020-03-29 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0011_merge_20200328_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='myaccount', to=settings.AUTH_USER_MODEL),
        ),
    ]
