# Generated by Django 2.2.3 on 2020-03-29 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0012_auto_20200329_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date1', models.DateField()),
                ('Time1', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='isVegan',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
