# Generated by Django 2.2.3 on 2020-03-29 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0013_auto_20200329_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='veganSince',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
    ]
