# Generated by Django 2.2.3 on 2020-03-30 15:36

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0014_auto_20200329_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='Date1',
        ),
        migrations.RemoveField(
            model_name='location',
            name='Time1',
        ),
        migrations.AddField(
            model_name='location',
            name='age',
            field=models.IntegerField(choices=[(18, 25), (25, 35), (35, 45), (45, 55), (55, 65), (65, 75), (75, 85), (95, 100)], default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='date1',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='location',
            name='date2',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='location',
            name='date3',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='location',
            name='gender',
            field=models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('NO PREFERENCE', 'no preference')], default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='time1',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='location',
            name='time2',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='location',
            name='time3',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender_mf',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
