# Generated by Django 2.2.3 on 2020-03-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0015_auto_20200330_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gender_mf',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(blank=True, default=3),
        ),
    ]
