# Generated by Django 2.2.3 on 2020-03-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0016_auto_20200330_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=20),
        ),
    ]
