# Generated by Django 2.2.3 on 2020-03-30 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0017_userprofile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
    ]
