# Generated by Django 2.2.3 on 2020-03-30 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0019_auto_20200330_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
    ]
