# Generated by Django 2.2.1 on 2020-03-30 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0020_remove_userprofile_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='meetupID',
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
