# Generated by Django 2.2.1 on 2020-03-30 21:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veganation', '0022_rental'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField(default=datetime.date.today)),
                ('time1', models.TimeField(default=django.utils.timezone.now)),
                ('date2', models.DateField(default=datetime.date.today)),
                ('time2', models.TimeField(default=django.utils.timezone.now)),
                ('date3', models.DateField(default=datetime.date.today)),
                ('time3', models.TimeField(default=django.utils.timezone.now)),
                ('age', models.IntegerField(choices=[(18, 25), (25, 35), (35, 45), (45, 55), (55, 65), (65, 75), (75, 85), (95, 100)])),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('NO PREFERENCE', 'no preference')], max_length=7)),
                ('meetupID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
