# Generated by Django 2.2.1 on 2020-03-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0023_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='gender',
            field=models.IntegerField(default=2),
        ),
    ]
