# Generated by Django 2.2.1 on 2020-03-31 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0006_auto_20200320_1206 copy'),
        ('veganation', '0025_auto_20200331_1155'),
    ]

    operations = [
    ]
