# Generated by Django 2.2.3 on 2020-03-31 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0026_auto_20200331_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='date1',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='location',
            name='date2',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='location',
            name='date3',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='veganSince',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
