# Generated by Django 2.2.1 on 2020-03-31 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0026_auto_20200331_1935'),
        ('veganation', '0027_location_meetupid'),
    ]

    operations = [
    ]
