# Generated by Django 2.2.1 on 2020-03-31 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0028_merge_20200331_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='meetupID',
        ),
    ]
