# Generated by Django 2.2.1 on 2020-03-31 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veganation', '0029_remove_location_meetupid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='time1',
        ),
        migrations.RemoveField(
            model_name='location',
            name='time2',
        ),
        migrations.RemoveField(
            model_name='location',
            name='time3',
        ),
        migrations.AddField(
            model_name='location',
            name='meetupID',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
