# Generated by Django 2.2.1 on 2020-03-31 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0030_auto_20200331_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='meetupID',
        ),
    ]
