# Generated by Django 2.2.1 on 2020-03-31 20:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0032_auto_20200331_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='idnum',
            field=models.IntegerField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
