# Generated by Django 2.2.1 on 2020-03-31 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0033_auto_20200331_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='idnum',
        ),
    ]
