# Generated by Django 2.2.1 on 2020-03-31 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veganation', '0036_auto_20200331_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='userBuddy',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
