# Generated by Django 2.2.1 on 2020-03-31 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0037_location_userbuddy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='userBuddy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
