# Generated by Django 2.2.1 on 2020-03-31 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0038_auto_20200331_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='userBuddy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
