# Generated by Django 2.2.1 on 2020-03-31 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0028_auto_20200331_2212'),
        ('veganation', '0039_auto_20200331_2058'),
    ]

    operations = [
    ]
