# Generated by Django 2.2.1 on 2020-03-31 22:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0040_merge_20200331_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='restaurant',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='date1',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='location',
            name='date2',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='location',
            name='date3',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
