# Generated by Django 2.2.3 on 2020-04-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0041_auto_20200331_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='veganSince',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
