# Generated by Django 2.2.1 on 2020-04-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0042_auto_20200401_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='location',
            name='rest',
            field=models.IntegerField(default=2),
        ),
    ]
