# Generated by Django 2.2.3 on 2020-04-01 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veganation', '0043_auto_20200401_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=128)),
                ('hug_rate', models.IntegerField(blank=True, null=True)),
                ('seren_rate', models.IntegerField(blank=True, null=True)),
                ('the78_rate', models.IntegerField(blank=True, null=True)),
                ('glasvegan_rate', models.IntegerField(blank=True, null=True)),
                ('puti_rate', models.IntegerField(blank=True, null=True)),
                ('mono_rate', models.IntegerField(blank=True, null=True)),
                ('picnic_rate', models.IntegerField(blank=True, null=True)),
                ('vandv_rate', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
