# Generated by Django 2.2.1 on 2020-04-02 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0044_rate'),
        ('veganation', '0047_auto_20200401_1358'),
    ]

    operations = [
    ]
