# Generated by Django 2.2.1 on 2020-04-02 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0052_auto_20200402_1317'),
        ('veganation', '0053_auto_20200402_1222'),
    ]

    operations = [
    ]
