# Generated by Django 2.2.3 on 2020-04-02 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0053_auto_20200402_1222'),
        ('veganation', '0052_auto_20200402_1317'),
    ]

    operations = [
    ]
