# Generated by Django 2.2.3 on 2020-04-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0052_auto_20200402_1317'),
        ('veganation', '0054_auto_20200402_1318'),
    ]

    operations = [
    ]
