# Generated by Django 2.2.3 on 2020-04-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0055_auto_20200402_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, default='prefer not to say', max_length=40),
        ),
    ]
