# Generated by Django 2.2.3 on 2020-04-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0055_auto_20200402_1448'),
        ('veganation', '0056_auto_20200402_1328'),
    ]

    operations = [
    ]
