# Generated by Django 2.2.3 on 2020-04-02 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0057_merge_20200402_1352'),
        ('veganation', '0056_auto_20200402_1503'),
    ]

    operations = [
    ]
