# Generated by Django 2.2.1 on 2020-04-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veganation', '0058_merge_20200402_1636'),
        ('veganation', '0055_auto_20200402_1321'),
        ('veganation', '0058_merge_20200402_1834'),
    ]

    operations = [
    ]
